<a href="https://colab.research.google.com/github/sanhith-lab/generative_ai_2251/blob/main/LAB_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
y_pred = np.array([0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2])

conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)

print("Confusion Matrix:")
print(conf_matrix)
print(f"\nAccuracy: {accuracy:.4f}")


Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Accuracy: 0.3333


In [9]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score
y_actual =np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
y_pred = np.array([0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2])
# The function name was misspelled as 'cofusion_matrix'.
# Correcting it to 'confusion_matrix':
conf_matrix = confusion_matrix(y_actual,y_pred)
accuracy = accuracy_score(y_actual,y_pred)
precision = precision_score(y_actual,y_pred,average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Accuracy")
print(accuracy)
print(precision)

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy
0.3333333333333333
0.3333333333333333


In [11]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score

y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)
precision_macro = precision_score(y_actual, y_pred, average='macro')
precision_micro = precision_score(y_actual, y_pred, average='micro')
precision_weighted = precision_score(y_actual, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision (Macro): {precision_macro:.4f}")
print(f"Precision (Micro): {precision_micro:.4f}")
print(f"Precision (Weighted): {precision_weighted:.4f}")


Confusion Matrix:
[[3 2]
 [2 3]]
Accuracy: 0.6000
Precision (Macro): 0.6000
Precision (Micro): 0.6000
Precision (Weighted): 0.6000


In [12]:
from scipy.optimize import linprog

# Linear Programming Problem
c = [-4, -5, -6]  # Coefficients for maximization (negative because linprog minimizes by default)
A = [[2, 1, 1], [4, 3, 0]]  # Coefficients for inequality constraints
b = [14, 20]  # Right-hand side values for inequality constraints
bounds = [(0, None), (0, None), (0, None)]  # X, Y, Z >= 0

result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

print("Linear Programming Solution:")
print(f"Optimal Values: X={result.x[0]:.4f}, Y={result.x[1]:.4f}, Z={result.x[2]:.4f}")
print(f"Maximum P: {-result.fun:.4f}")


Linear Programming Solution:
Optimal Values: X=0.0000, Y=0.0000, Z=14.0000
Maximum P: 84.0000


In [21]:
from scipy.optimize import linprog
c =[-40,-30]
A=[1,2],[2,3]
b=[40,60]
bounds = [(0,None),(0,None)]
result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')
print(f"Optimal Values: a={result.x[0]:.4f},b={result.x[1]:.4f}")
print(f"Maximum P: {-result.fun:.4f}")

Optimal Values: a=30.0000,b=0.0000
Maximum P: 1200.0000


In [23]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Actual and Predicted Values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])
mse_manual = np.sum((y_actual - y_pred) ** 2) / len(y_actual)
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)
rmse_manual = np.sqrt(mse_manual)
mse_sklearn = mean_squared_error(y_actual, y_pred)
mae_sklearn = mean_absolute_error(y_actual, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)

# Print results
print("Error Metrics Calculation:")
print(f"Manual MSE: {mse_manual:.4f}")
print(f"Sklearn MSE: {mse_sklearn:.4f}")
print(f"Manual MAE: {mae_manual:.4f}")
print(f"Sklearn MAE: {mae_sklearn:.4f}")
print(f"Manual RMSE: {rmse_manual:.4f}")
print(f"Sklearn RMSE: {rmse_sklearn:.4f}")

Error Metrics Calculation:
Manual MSE: 0.1850
Sklearn MSE: 0.1850
Manual MAE: 0.4000
Sklearn MAE: 0.4000
Manual RMSE: 0.4301
Sklearn RMSE: 0.4301
